# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts-alpine


# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/

deploy:
  stage: deploy
  dependencies:
    - build
  before_script:
    - curl --location --remote-name https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
    - echo "$GCP_KEY" | base64 --decode --ignore-garbage > gcloud-service-key.json
    - cp gcloud-service-key.json ./infra/gcloud-service-key.json
    - tar xvf google-cloud-sdk.tar.gz
    - ./google-cloud-sdk/install.sh --quiet
    - source ./google-cloud-sdk/path.bash.inc
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud config set run/region us-east1
  script:
      - npm run deploy
  environment: production
